"""create loan products table

Revision ID: 0c5754eb4161
Revises: 6ec7df72f1cb
Create Date: 2026-09-21 15:27:05.552152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5754eb4161'
down_revision: Union[str, Sequence[str], None] = '6ec7df72f1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('min_loan_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('max_loan_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_tenure_months', sa.Integer(), nullable=False),
    sa.Column('max_tenure_months', sa.Integer(), nullable=False),
    sa.Column('base_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_index(op.f('ix_loan_products_id'), 'loan_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_products_id'), table_name='loan_products')
    op.drop_table('loan_products')
    # ### end Alembic commands ###
