"""add unique constraint to repayments

Revision ID: 4110cf7b4362
Revises: b585dd5014b4
Create Date: 2026-09-22 10:26:17.079550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4110cf7b4362'
down_revision: Union[str, Sequence[str], None] = 'b585dd5014b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_repayment_loan_installment', 'repayments', ['loan_account_id', 'installment_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repayment_loan_installment', 'repayments', type_='unique')
    # ### end Alembic commands ###
