"""create interest rates table

Revision ID: 8d9bf50265f4
Revises: 0c5754eb4161
Create Date: 2026-09-21 15:32:02.637802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d9bf50265f4'
down_revision: Union[str, Sequence[str], None] = '0c5754eb4161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_product_id', sa.Integer(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loan_product_id'], ['loan_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_rates_id'), 'interest_rates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interest_rates_id'), table_name='interest_rates')
    op.drop_table('interest_rates')
    # ### end Alembic commands ###
