"""add repayment principal and interest components

Revision ID: b585dd5014b4
Revises: 0165a9feba3d
Create Date: 2026-09-22 09:48:28.404276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b585dd5014b4'
down_revision: Union[str, Sequence[str], None] = '0165a9feba3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repayments', sa.Column('principal_component', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('repayments', sa.Column('interest_component', sa.Numeric(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repayments', 'interest_component')
    op.drop_column('repayments', 'principal_component')
    # ### end Alembic commands ###
